Repository drupal-graphql/graphql, pull requests merged in 2019-10, with the labels that each got.

#909 Entity revisions data producer
  graphql.services.yml
  src/GraphQL/Buffers/EntityRevisionBuffer.php
  src/Plugin/GraphQL/DataProducer/Field/EntityReferenceRevisions.php
Labels: 4.x

#850 docs(queries): Fix throwing exception problem
  doc/queries/nodes.md
  doc/queries/routes.md
Labels: documentation

#925 EntityFieldPropertyDeriver overrides parents
  modules/graphql_core/src/Plugin/Deriver/Fields/EntityFieldPropertyDeriver.php
Labels: 3.x, release blocker
