Repository drupal-graphql/graphql, pull requests merged in 2019-06, with the labels that each got.

#792 Introduce extended schema plugin.
  src/Plugin/GraphQL/Schema/SdlExtendedSchemaPluginBase.php
  src/Plugin/GraphQL/Schema/SdlSchemaPluginBase.php
Labels: 4.x

#781 fix(ImageDerivative): allow passing NULL
  src/Plugin/GraphQL/DataProducer/Entity/Fields/Image/ImageDerivative.php
Labels: 4.x

#769 fix(entity_load): Name changes in annotation
  src/Plugin/GraphQL/DataProducer/Entity/EntityLoad.php
Labels: 4.x

#774 Fix broken authentication
  graphql.services.yml
  src/Routing/QueryRoutes.php
Labels: release blocker

#753 feat(Entity): Include Entity load multiple producer
  src/Plugin/GraphQL/DataProducer/Entity/EntityLoadMultiple.php
  tests/src/Kernel/DataProducer/EntityMultipleTest.php
Labels: 4.x

#762 fix(travis): Use correct webonyx/graphql-php version, same as in composer.json
  .travis.yml
Labels: 4.x

#731 Derive typed data type from given value by default.
  src/Plugin/GraphQL/DataProducer/TypedData/PropertyPath.php
  tests/src/Kernel/DataProducer/TypedDataTest.php
Labels: 4.x

#817 Graphql 4x docs
  doc/...md
  doc/README.md
  doc/SUMMARY.md
  doc/advanced/split-schema.md
  doc/authentication/introduction.md
  doc/getting-started/getting-started.md
  doc/metatag-seo/metatag.md
  doc/mutations/README.md
  doc/mutations/creating-mutation-plugins.md
  doc/mutations/mutations.md
  doc/producers/README.md
  doc/producers/built-in.md
  doc/producers/composing.md
  doc/producers/custom.md
  doc/queries/README.md
  doc/queries/filters.md
  doc/queries/menus.md
  doc/queries/nodes.md
  doc/queries/queries.md
  doc/queries/query-fragments.md
  doc/queries/querying-nodes.md
  doc/queries/querying-taxonomies.md
  doc/queries/references.md
  doc/queries/routes.md
  doc/queries/variables.md
  doc/starting/README.md
  doc/starting/custom-schema.md
  doc/upgrade/beta6.md
Labels: 4.x, documentation
