Repository drupal-graphql/graphql, pull requests merged in 2020-11, with the labels that each got.

#1087 Remove `getSchemaDefinitions` from GraphQLTestBase
  tests/src/Kernel/GraphQLTestBase.php
Labels: 4.x

#1086 Update GraphQL PHP dependency to v14.3.0
  .travis.yml
  composer.json
  config/schema/graphql.schema.yml
  graphql.install
  src/Entity/Server.php
  src/Form/ServerForm.php
  src/GraphQL/Resolver/Composite.php
  src/GraphQL/Resolver/Condition.php
  src/GraphQL/Resolver/DefaultValue.php
  src/GraphQL/Utility/DeferredUtility.php
  tests/src/Traits/DataProducerExecutionTrait.php
Labels: 4.x

#1023 Avoid redirect in link in documentation
  README.md
Labels: 4.x, documentation

#1056 Fixes typo in custom-schema.md.
  doc/starting/custom-schema.md
Labels: 4.x, documentation

#1092 Added missing closing bracket
  doc/queries/menus.md
Labels: 4.x, documentation

#1024 Support all default field types for Entity Definitions Default Value resolver
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/DefaultValue.php
Labels: 4.x

#1103 tests(coder): Update Coder to 8.3.11
  .travis.yml
  src/Entity/Server.php
  src/GraphQL/Execution/Executor.php
  src/GraphQL/Resolver/Path.php
  src/GraphQL/ResolverRegistryInterface.php
  src/Plugin/GraphQL/DataProducer/DataProducerPluginBase.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLink/MenuLinkAttribute.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLink/MenuLinkDescription.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLink/MenuLinkExpanded.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLink/MenuLinkLabel.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLink/MenuLinkUrl.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuLinks.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuTree/MenuTreeLink.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuTree/MenuTreeSubtree.php
  src/Plugin/GraphQL/DataProducer/Routing/RouteLoad.php
  src/Plugin/GraphQL/DataProducer/Routing/Url/UrlPath.php
  src/Plugin/GraphQL/Schema/ComposableSchema.php
  src/Plugin/SchemaPluginInterface.php
  tests/src/Kernel/DataProducer/Entity/Fields/Image/ImageDerivativeTest.php
  tests/src/Kernel/DataProducer/Entity/Fields/Image/ImageUrlTest.php
  tests/src/Kernel/DataProducer/EntityTest.php
  tests/src/Kernel/DataProducer/Routing/RouteEntityTest.php
Labels: 4.x

#1109 update example to use EntityTypeManager
  examples/graphql_example/src/Plugin/GraphQL/DataProducer/QueryArticles.php
Labels: 4.x

#1105 feat(data-producer): Introducing a taxonomy term autocomplete data producer.
  graphql.api.php
  src/Plugin/GraphQL/DataProducer/Taxonomy/TermFieldAutocomplete.php
Labels: 4.x

#1108 test(github): Add Github Actions config
  .github/workflows/testing.yml
  .travis.yml
  README.md
Labels: 4.x

#1104 test(phpstan): Increase PHPStan level to 4
  phpstan.neon
  src/Access/QueryAccessCheck.php
  src/GraphQL/Resolver/Condition.php
  src/GraphQL/Resolver/Path.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/DefaultValue.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Description.php
  src/Plugin/GraphQL/DataProducer/Field/EntityReference.php
  src/Plugin/GraphQL/DataProducer/Field/EntityReferenceLayoutRevisions.php
  src/Plugin/GraphQL/DataProducer/Field/EntityReferenceRevisions.php
  src/Plugin/GraphQL/DataProducer/Menu/MenuTree/MenuTreeSubtree.php
  src/Plugin/GraphQL/DataProducer/Routing/RouteLoad.php
  src/Plugin/PersistedQueryPluginInterface.php
Labels: 4.x

#818 Add a file upload utility
  graphql.services.yml
  src/GraphQL/Utility/FileUpload.php
  src/Wrappers/FileUploadResponse.php
  src/Wrappers/FileUploadResponseInterface.php
Labels: 4.x

#1112 feat(files): Add File upload service wit tests
  .github/workflows/testing.yml
  phpstan.neon
  src/GraphQL/Response/FileUploadResponse.php
  src/GraphQL/Utility/FileUpload.php
  tests/src/Kernel/Framework/MockFileSystem.php
  tests/src/Kernel/Framework/UploadFileServiceTest.php
Labels: 4.x

#1118 fix(files): Fix lock release handling when the file upload does not validate
  src/GraphQL/Utility/FileUpload.php
  tests/src/Kernel/Framework/UploadFileServiceTest.php
Labels: 4.x

#1080 Fix warning for non-variables passed by reference
  src/Form/ServerForm.php
Labels: 4.x, needs tests
