Repository drupal-graphql/graphql, pull requests merged in 2020-02, with the labels that each got.

#970 Add note about debugging produers.
  doc/producers/composing.md
Labels: 4.x, documentation

#969 Create images.md
  doc/queries/images.md
Labels: 4.x, documentation

#966 Check if the given image style is supported.
  modules/graphql_core/src/Plugin/GraphQL/Fields/Entity/Fields/Image/ImageDerivative.php
Labels: 3.x

#959 Update Path Alias API deprecations
  modules/graphql_core/src/Plugin/GraphQL/Fields/Routing/InternalUrl/Alias.php
  modules/graphql_core/tests/src/Kernel/Routing/RouteTest.php
Labels: 3.x

#958 Drop support for EOL Drupal 8.6
  .travis.yml
Labels: 3.x

#971 ADD graphiql-explorer to make it more accessible
  assets/explorer/dist/bundle.min.js
  assets/explorer/dist/container.css
  assets/explorer/dist/graphiql.css
  assets/explorer/package-lock.json
  assets/explorer/package.json
  assets/explorer/src/Explorer.js
  assets/explorer/src/container.css
  assets/explorer/src/index.js
Labels: 4.x

#947 fix undefined index schema
  src/Form/ServerForm.php
Labels: 4.x, enhancement

#941 Add a "defaultValue" to the resolver builder.
  src/GraphQL/Resolver/DefaultValue.php
  src/GraphQL/ResolverBuilder.php
  tests/src/Kernel/ResolverBuilderTest.php
Labels: 4.x, enhancement

#928 Refactor entity buffer resolver so that duplicate entity IDs are not dropped
  src/GraphQL/Buffers/EntityBuffer.php
Labels: 4.x

#929 Allow to obtain field name property from field context.
  src/GraphQL/Execution/FieldContext.php
Labels: 4.x

#951 Accept EntityTypeManagerInterface in TaxonomyLoadTree
  src/Plugin/GraphQL/DataProducer/Taxonomy/TaxonomyLoadTree.php
Labels: 4.x, enhancement

#953 Fix TaxonomyLoadTree::resolve return typehint
  src/Plugin/GraphQL/DataProducer/Taxonomy/TaxonomyLoadTree.php
Labels: 4.x, enhancement

#860 Entity definition data producers.
  src/Plugin/GraphQL/DataProducer/EntityDefinition/EntityDefinition.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/DefaultValue.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Description.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Hidden.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Id.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Label.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/MaxNumItems.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Multiple.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Reference.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Required.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Settings.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Status.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Type.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Fields/Weight.php
  src/Plugin/GraphQL/DataProducer/EntityDefinition/Label.php
Labels: 4.x

#968 Added entity reference layout revisions plugin.
  src/Plugin/GraphQL/DataProducer/Field/EntityReferenceLayoutRevisions.php
Labels: 4.x, feature
