Repository drupal-graphql/graphql, pull requests merged in 2023-09, with the labels that each got.

#1242 Fixes deprecated call to file url.
  modules/graphql_core/src/Plugin/GraphQL/Fields/Entity/Fields/Image/ImageDerivative.php
Labels: 3.x

#1110 List path_alias as required for graphql_core
  modules/graphql_core/graphql_core.info.yml
Labels: 3.x

#999 Added Example of all features of queries
  doc/queries/README.md
Labels: documentation, 3.x

#979 #926 - Add layout section scalar type
  src/Plugin/GraphQL/Scalars/Internal/LayoutSectionScalar.php
Labels: 3.x

#996 Merge caching for entity fields
  modules/graphql_core/src/Plugin/GraphQL/Fields/EntityFieldBase.php
Labels: 3.x

#1340 Tiny bug in `Condition`
  src/GraphQL/Resolver/Condition.php
  tests/src/Kernel/ResolverBuilderTest.php
Labels: bug, 4.x
